sudo: false
language: ruby
cache:
  bundler: true
rvm:
  - "2.2.6"
  - "2.3.3"
gemfile:
  - Gemfile
  - test/gemfiles/Gemfile-Rails-4.2
env:
  - ADAPTER=mysql2
  - ADAPTER=postgresql
before_script:
  - rake db:mysql:build
  - rake db:postgresql:build
